CodeAcademy/Areas/Edu/Models/ViewModels/BookViewModel.cs
using CodeAcademy.Areas.Editor.Models.ViewModels;
using CodeAcademy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeAcademy.Areas.Edu.Models.ViewModels
{
    public class BookViewModel
    {
        public BookViewModel(Book book)
        {
            this.Id = book.Id;
            this.Name = book.Name;
            this.Author = book.Author;
            this.Description = book.Description;
            this.Language = book.Language.Name;
            this.PageCount = book.PageCount;
            this.ImagePath = book.Image.Path;
            this.FilePath = book.FilePath;
            this.LikeCount = book.Likes.Count;
            this.Tags = book.TagPosts.Select(x => new TagViewModel{ Id = x.TagId,  Name = x.Tag.Name}) .ToList();
        }
        public  int Id { get; set; }

        public string Name { get; set; }

        public string Author { get; set; }

        public string Description { get; set; }

        public string Language { get; set; }

        public short PageCount { get; set; }    

        public string ImagePath { get; set; }

        public string FilePath { get; set; }

        public int LikeCount { get; set; }

        public List<TagViewModel> Tags { get; set; }
    }
}

CodeAcademy/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeAcademy.Models
{
    public class Book:Post
    {
        public string Author { get; set; } 

        public string Name { get; set; }

        public string Description { get; set; }

        public short PageCount { get; set; } 

        public int LanguageId { get; set; }
        public Language Language { get; set; }

        public string FilePath { get; set; }    

        public bool IsApproved { get; set; }

        public int ImageId { get; set; }
        public Image Image { get; set; }
    }
}

CodeAcademy/Areas/Edu/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CodeAcademy.Areas.Admin.Models.ViewModels;
using CodeAcademy.Areas.Edu.Models;
using CodeAcademy.Areas.Edu.Models.ViewModels;
using CodeAcademy.Models;
using CodeAcademy.Models.ViewModels;
using CodeAcademy.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CodeAcademy.Areas.Edu.Controllers
{
    [Authorize(Roles = "Student,Teacher")]
    [Area("Edu")]
    public class BooksController : Controller
    {
        AppDbContext _dbContext;
        UserManager<User> _userManager;
        IHostingEnvironment _environment;

        public BooksController(AppDbContext dbContext, UserManager<User> userManager, IHostingEnvironment environment)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _environment = environment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(BookCreateModel model)
        {
            if (ModelState.IsValid)
            {
                string[] tags = model.Tags.Split(',');
                List<Tag> bookTags = new List<Tag>();
                foreach (var tag in tags)
                {
                    Tag t = await _dbContext.Tags.FirstOrDefaultAsync(x => x.Name.ToLower() == tag.Trim().ToLower());
                    bookTags.Add(t);
                }

                Image img = new Image() { Path = Path.Combine("/images", model.Cover.FileName) };
                await _dbContext.Images.AddAsync(img);

                await Uploader.UploadToServer(new Uploader(_environment).DefineBookPath(model.Book), model.Book);
                await Uploader.UploadToServer(new Uploader(_environment).DefineImagePath(model.Cover), model.Cover);

                Book book = new Book()
                {
                    Author = model.Author,
                    CreationDate = DateTime.Now,
                    Description = model.Description,
                    Language = await _dbContext.Languages.FirstOrDefaultAsync(x=>x.Id==model.LanguageId),
                    PageCount = model.PageCount,
                    Name = model.Name,
                    FilePath = Path.Combine("/books", model.Book.FileName),
                    Image = img,
                    Faculty = await _dbContext.Faculties.FirstOrDefaultAsync(x => x.Id == model.FacultyId),
                    User = await _userManager.Users.FirstOrDefaultAsync(x => x.Email == HttpContext.User.Identity.Name)
                };

                List<TagPost> tagPosts = new List<TagPost>();
                foreach (var tag in bookTags)
                {
                    tagPosts.Add(new TagPost() { Post = book, Tag = tag });
                }

                book.TagPosts = tagPosts;

                if (await _dbContext.Books.AddAsync(book) != null)
                {
                    if (await _dbContext.SaveChangesAsync() > 0)
                    {
                        return Json(new BookViewModel(book));
                    }
                }
                else
                {
                    return Json("Wrong!!!");
                }
            }
            else
            {
                ModelState.AddModelError("","Check your inputs");
            }
            return Ok();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllBooks()
        {
            var allBooks = await _dbContext.Books.Include(x => x.Image)
                                                    .Include(x => x.Language)
                                                       .Include(x => x.TagPosts).ThenInclude(t=>t.Tag)
                                                          .Include(x => x.Likes)
                                                             .ToListAsync();
            var model = allBooks.Select(x => new BookViewModel(x)).ToList();
            return Json(model);
        }

        [HttpPost]
        public async Task<IActionResult> GetTagsByFacultyId(int id)
        {
            var tags = await _dbContext.Tags.Where(x => x.FacultyId == id)
                                            .Select(d => new DropdownViewModel { Id = d.Id, Name = d.Name })
                                            .ToListAsync();
            return Json(tags);
        }

        [HttpGet]
        public IActionResult GetFaculties()
        {
            var data = _dbContext.Faculties.Select(x => new DropdownViewModel() { Id = x.Id, Name = x.Name }).ToList();
            return Json(data);
        }

        [HttpGet]
        public IActionResult GetLanguages()
        {
            var data = _dbContext.Languages.Select(x => new DropdownViewModel() { Id = x.Id, Name = x.Name }).ToList();
            return Json(data);
        }

        [HttpPost]
        public async Task<IActionResult> GetBooksByFaculty(int facultyId)
        {
            var books = await _dbContext.Books.Where(x => x.FacultyId == facultyId)
                                              .Include(x => x.Language)
                                              .Include(x => x.TagPosts).ThenInclude(t => t.Tag)
                                              .Include(x => x.Image)
                                              .Include(x => x.Likes)
                                              .ToListAsync();

            var data = books.Select(x => new BookViewModel(x));
            return Json(data);
        }

        [HttpPost]
        public async Task<IActionResult> GetBooksByLanguage(int languageId)
        {
            var books = await _dbContext.Books.Where(x => x.LanguageId == languageId)
                                  .Include(x => x.Language)
                                  .Include(x => x.TagPosts).ThenInclude(t => t.Tag)
                                  .Include(x => x.Image)
                                  .Include(x => x.Likes)
                                  .ToListAsync();

            var data = books.Select(x => new BookViewModel(x));
            return Json(data);
        }

        [HttpPost]
        public async Task<IActionResult> SearchBookByName(BookSearchModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _dbContext.Books.Include(x => x.Image)
                                                    .Include(x => x.Language)
                                                    .Include(x => x.TagPosts).ThenInclude(t=>t.Tag)
                                                    .Include(x => x.Likes)
                                                    .Where(x => x.Name.ToLower().Contains(model.Name.ToLower()))
                                                    .Select(x => new BookViewModel(x))
                                                    .ToListAsync();
                return Json(result);
            }
            return Json("No books found...");
        }
    }
}

CodeAcademy/Areas/Edu/Views/Books/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<body>
    @await Component.InvokeAsync("UpperPanel", new { email = User.Identity.Name })

    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <input type="button" class="btn btn-info" id="open-create-book" value="New Book" />
                <input type="button" id="show-all" class="btn btn-warning" value="All Books" />
            </div>
        </div>
    </div>
    <br />

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8">
                <ul class="list-group" id="books"></ul>
            </div>
            <div class="col-sm-4">
                <form id="search" method="post" asp-area="Edu" asp-controller="Books" asp-action="SearchBookByName" >
                    <label>Book search</label>
                    <input class="form-control" name="name" type="text" placeholder="Enter book name..." aria-label="Search">
                    <br />
                    <input type="submit" class="btn btn-info" value="Search book" />
                </form>
                <br />

                <form asp-area="Edu" asp-controller="Books" asp-action="GetBooksByFaculty" method="post">
                    <label>Faculty</label>
                    <select name="facultyid" id="faculty-search" class="form-control"></select>
                </form>
                <br />

                <form asp-area="Edu" asp-controller="Books" asp-action="GetBooksByLanguage" method="post">
                    <label>Language</label>
                    <select name="languageid" id="language-search" class="form-control"></select>
                </form>
            </div>
        </div>
    </div>


    @* New book form *@
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div id="new-book" class="custom-modal">
                    <h5 class="h5 text-center">New Book</h5>
                    <form id="bookform" asp-area="Edu" asp-controller="Books" asp-action="Add" class="form-group" method="post" enctype="multipart/form-data">
                        <label>Faculty</label>
                        <select name="facultyid" id="faculty" class="form-control"></select>
                        <label>Author</label>
                        <input type="text" class="form-control" id="author" required name="author" value="" />
                        <label>Name</label>
                        <input type="text" class="form-control" id="name" required name="name" value="" />
                        <label>Description</label>
                        <input type="text" class="form-control" id="description" required name="description" value="" />
                        <label>Language</label>
                        <select name="languageid" id="language" class="form-control"></select>
                        <label>Page count</label>
                        <input type="number" class="form-control" required id="pagecount" name="pagecount" value="" />
                        <input type="file" name="book" id="book" required accept="application/pdf" class="btn file btn-info" value="Upload Book" />
                        <input type="file" name="cover" id="cover" required accept="image/*" class="btn file btn-info" value="Upload Book" />
                        <br />
                        <input type="text" readonly name="tags" class="form-control" id="book-tags"/>
                        <input type="submit" value="Create Book" id="submit-create" class="btn btn-success" />
                        <input type="button" value="Close" id="close-create-book" class="btn btn-danger" />
                    </form>
                </div>
            </div>
        </div>
    </div>


    <style>
        .book{
            display:inline-block;
            height:15vh;
        }
        .book a *{
            display:inline;
        }
        .custom-modal {
            padding: 2vh;
            display: none;
            position: fixed;
            width: 25vw;
            z-index: 3;
            top: 5vh;
            left: 35vw;
            overflow: auto;
            border: 1px solid black;
            border-radius: 1vh;
            background-color: #ababab;
        }
        .cover{
            height:100%;
        }
    </style>

    <script>
        var facTags = [];
        var bookTags = [];
        $("#open-create-book").click(function () {
            $("#new-book").css("display", "block");
            $.ajax({
                method: "POST",
                url: "/Edu/Books/GetTagsByFacultyId/id",
                data: {
                    id: $("#faculty").val()
                }
            })
                .done(function (obj) {
                    for (var i = 0; i < obj.length; i++) {
                        facTags.push(obj[i].name.toLowerCase())
                    }
                })
                .fail(function (msg) {
                    console.log(msg)
                })
        });

        $("#close-create-book").click(function () {
            $("#new-book").css("display", "none");
        });


        $.ajax({
            method: "GET",
            url: "/Edu/Books/GetFaculties",
            success: function (data) {
                for (var i = 0; i < data.length; i++) {
                    var fac = document.createElement("option");
                    fac.value = data[i].id;
                    fac.innerText = data[i].name
                    document.getElementById("faculty").appendChild(fac);
                    var facs = document.createElement("option");
                    facs.value = data[i].id;
                    facs.innerText = data[i].name
                    document.getElementById("faculty-search").appendChild(facs);
                }
            },
        });

        $.ajax({
            method: "GET",
            url: "/Edu/Books/GetLanguages",
            success: function (data) {
                for (var i = 0; i < data.length; i++) {
                    var lan = document.createElement("option");
                    lan.value = data[i].id;
                    lan.innerText = data[i].name
                    document.getElementById("language").appendChild(lan);
                    var lans = document.createElement("option");
                    lans.value = data[i].id;
                    lans.innerText = data[i].name
                    document.getElementById("language-search").appendChild(lans);
                }
            },
        });

        var files = [];
        var fileReader = new FileReader()
        $('input[type=file]').on('change', function (e) {
            files.push(e.target.files[0]);
        });

        $("#faculty").change(function (e) {
            facTags = [];
            bookTags = [];
            $.ajax({
                method: "POST",
                url: "/Edu/Books/GetTagsByFacultyId/id",
                data: {
                    id: $(e.target).val()
                }
            })
                .done(function (obj) {
                    for (var i = 0; i < obj.length; i++) {
                        facTags.push(obj[i].name.toLowerCase())
                    }
                })
                .fail(function (msg) {
                    console.log(msg)
                })
        });

        $("#description").keyup(function (e) {
            var text = $(e.target).val()
            var textArr = text.split(" ")
            for (var i = 0; i < textArr.length; i++) {
                if (facTags.indexOf(textArr[i].toLowerCase()) != -1 && bookTags.indexOf(textArr[i].toLowerCase()) < 0) {
                    bookTags.push(textArr[i].toLowerCase())
                }
            }
        });

        $("#description").blur(function () {
            var taglist = "";
            $("#book-tags").val("");
            for (var i = 0; i < bookTags.length; i++) {
                var tag = bookTags[i] + " , ";
                taglist += tag;
            }
            document.getElementById("book-tags").value = taglist.substring(0, taglist.length - 2);
        });

        $.ajax({
            method: "GET",
            url: "/Edu/Books/GetAllBooks",
            success: function (data) {
                for (var i in data) {
                }
                FillBooksOnPage(data)
            }
        });

        $("#show-all").click(function () {
            document.getElementById("books").innerHTML = "";
            $.ajax({
                method: "GET",
                url: "/Edu/Books/GetAllBooks",
                success: function (data) {
                    FillBooksOnPage(data)
                }
            });
        });

        function FillBooksOnPage(data) {
            var books = document.getElementById("books");

            for (var i = 0; i < data.length; i++) {

                var book = document.createElement("li");
                book.classList.add("list-group-item", "book");

                var hiddenId = document.createElement("input");
                hiddenId.setAttribute("type", "hidden");
                hiddenId.value = data[i].id;

                var likeBtn = document.createElement("input");
                likeBtn.type = "button";
                likeBtn.classList.add("btn", "btn-success", "like");
                likeBtn.value = "Like" + " " + data[i].likeCount
                likeBtn.addEventListener("click", function (e) {
                    var bookId = $(e.target).next().val();
                    $.ajax({
                        method: "POST",
                        url: "/Edu/Home/LikePost/postId",
                        data: {
                            postId: bookId
                        }
                    })
                        .done(function (obj) {
                            console.log(obj)
                            var text = "Like " + obj;
                            $(e.target).val(text)
                        })
                        .fail(function (msg) {
                            console.log(msg)
                        })
                });

                var link = document.createElement("a");
                link.target = "_blank";
                link.href = data[i].filePath;

                book.appendChild(link);
                book.appendChild(likeBtn);
                book.appendChild(hiddenId);

                var cover = document.createElement("img");
                cover.classList.add("img", "img-responsive", "cover")
                cover.src = data[i].imagePath;
                link.appendChild(cover);
               
                var text = document.createElement("p");
                text.classList.add("lead");
                text.innerText = data[i].name + " - " + data[i].author;
                link.appendChild(text);

                books.appendChild(book);
            }
        }

        $("#faculty-search").change(function (e) {
            var facId = $(e.target).val();
            $.ajax({
                method: "POST",
                url: "/Edu/Books/GetBooksByFaculty/facultyId",
                data: {
                    facultyId: facId
                }
            })
                .done(function (obj) {
                    document.getElementById("books").innerHTML = "";
                    FillBooksOnPage(obj)
                })
                .fail(function (msg) {
                    console.log(msg)
                })
        })

        $("#language-search").change(function (e) {
            var lanId = $(e.target).val()
            $.ajax({
                method: "POST",
                url: "/Edu/Books/GetBooksByLanguage/languageId",
                data: {
                    languageId: lanId
                }
            })
                .done(function (obj) {
                    document.getElementById("books").innerHTML = "";
                    FillBooksOnPage(obj)
                })
                .fail(function (msg) {
                    console.log(msg)
                })
        });

    </script>
</body>
</html>